#pragma checksum "..\..\DashboardWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8863328F2723351A6995A6823B293E248D08647581DDBC468954C406DDC67DFB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Custome_Department_Truck_Inspection_System;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Custome_Department_Truck_Inspection_System {
    
    
    /// <summary>
    /// DashboardWindow
    /// </summary>
    public partial class DashboardWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 27 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TxtTruck;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TxtInspection;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TxtSafety;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TxtCargo;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TxtLegal;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TxtRecommendtion;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TxtData;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnLogout;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Custome Department Truck Inspection System;component/dashboardwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\DashboardWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtTruck = ((System.Windows.Controls.Button)(target));
            
            #line 27 "..\..\DashboardWindow.xaml"
            this.TxtTruck.Click += new System.Windows.RoutedEventHandler(this.TxtTruck_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TxtInspection = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\DashboardWindow.xaml"
            this.TxtInspection.Click += new System.Windows.RoutedEventHandler(this.TxtInspection_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TxtSafety = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\DashboardWindow.xaml"
            this.TxtSafety.Click += new System.Windows.RoutedEventHandler(this.TxtSafety_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.TxtCargo = ((System.Windows.Controls.Button)(target));
            
            #line 30 "..\..\DashboardWindow.xaml"
            this.TxtCargo.Click += new System.Windows.RoutedEventHandler(this.TxtCargo_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TxtLegal = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\DashboardWindow.xaml"
            this.TxtLegal.Click += new System.Windows.RoutedEventHandler(this.TxtLegal_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TxtRecommendtion = ((System.Windows.Controls.Button)(target));
            
            #line 32 "..\..\DashboardWindow.xaml"
            this.TxtRecommendtion.Click += new System.Windows.RoutedEventHandler(this.TxtRecommendtion_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TxtData = ((System.Windows.Controls.Button)(target));
            
            #line 33 "..\..\DashboardWindow.xaml"
            this.TxtData.Click += new System.Windows.RoutedEventHandler(this.TxtData_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BtnLogout = ((System.Windows.Controls.Button)(target));
            
            #line 34 "..\..\DashboardWindow.xaml"
            this.BtnLogout.Click += new System.Windows.RoutedEventHandler(this.BtnLogout_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

